export type Citation = { text: string; url: string; source: string };
export type Fact = { label: string; value: string; source?: string };
export type FAQItem = { q: string; a: string };
export type RecoveryStep = { period: string; title: string; description: string };

export type Procedure = {
  slug: string;
  title: string;
  h1: string;
  category: "augmentare" | "preput" | "curbura" | "reparator" | "regenerativ";
  procedureType: "SurgicalProcedure" | "NonSurgicalProcedure" | "TherapeuticProcedure";
  metaTitle: string;
  metaDescription: string;
  primaryKeyword: string;
  searchVolume: string;
  intent: string;
  bodyLocation: string;
  shortDescription: string;
  lead: string;
  cost: string;
  duration: string;
  recovery: string;
  anesthesia: string;
  hospitalStay: string;
  sexualActivity: string;
  whatIs: string;
  whenIndicated: string[];
  whenNotIndicated: string[];
  procedureSteps: { title: string; description: string }[];
  facts: Fact[];
  recovery_timeline: RecoveryStep[];
  risks: { title: string; description: string }[];
  alternatives: { title: string; description: string }[];
  faqs: FAQItem[];
  citations: Citation[];
  internalLinks: { slug: string; label: string }[];
  speakablePassages: string[];
  alternateName?: string[];
};

export const proceduri: Procedure[] = [
  {"slug":"alungire-penis","title":"Alungire penis chirurgicală","h1":"Alungire chirurgicală a penisului","category":"augmentare","procedureType":"SurgicalProcedure","metaTitle":"Alungire penis chirurgical București | Faloplastie 2-5 cm | Dr. Diana","metaDescription":"Alungire chirurgicală a penisului prin secționarea ligamentului suspensor.","primaryKeyword":"alungire penis chirurgical","searchVolume":"1.300-1.700/lună","intent":"Commercial-investigational","bodyLocation":"penis (joncțiune pubiană)","alternateName":["faloplastie dorsală","ligamentoliză"],"shortDescription":"Câștig vizual 2-5 cm prin secționarea ligamentului suspensor.","lead":"Studiu pe 1.200+ pacienți (Aesthet Plast Surg 2020) raportează 78% satisfacție. Câștig vizual 2-5 cm prin descoperirea segmentului intracorporal.","cost":"2.800-4.500 EUR","duration":"60-90 min","recovery":"7-10 zile","anesthesia":"Locală cu sedare","hospitalStay":"Externare aceeași zi","sexualActivity":"4-6 săptămâni","whatIs":"Faloplastie dorsală — secționarea parțială a ligamentului suspensor.","whenIndicated":["Micropenis","Indicație estetică","Penis ascuns parțial"],"whenNotIndicated":["Curbură peniană","Așteptări nerealiste","Fumat activ"],"procedureSteps":[{"title":"Anestezia","description":"Locală cu sedare 80% cazuri."},{"title":"Incizia","description":"1,5-2 cm pliu pubian."},{"title":"Secționarea","description":"75-80% din ligament."}],"facts":[{"label":"Câștig flasc","value":"2-5 cm","source":"Marquez-Algaba 2020"},{"label":"Câștig erecție","value":"1-3 cm"},{"label":"Satisfacție","value":"78%","source":"Aesthet Plast Surg 2020"},{"label":"Lungime medie globală","value":"13,12 cm","source":"Veale BJU 2015 (n=15.521)"}],"recovery_timeline":[{"period":"Zilele 1-3","title":"Disconfort moderat","description":"Repaus, paracetamol."},{"period":"Săpt. 4-6","title":"Reluare sexuală","description":"După acordul medicului."}],"risks":[{"title":"Echimoze","description":"15-30%."},{"title":"Regrete","description":"4-6%."}],"alternatives":[{"title":"HA","description":"Doar grosime."},{"title":"Lipofilling","description":"Pentru circumferință."}],"faqs":[{"q":"Voi pierde erecția?","a":"Nu. Ligamentul suspensor nu participă la mecanismul erectil."},{"q":"Cicatrice vizibilă?","a":"1,5-2 cm în pliul pubian, acoperită de pilozitate."},{"q":"Câți regretă?","a":"4-6% conform Vardi 2008."}],"citations":[{"text":"Veale D et al. BJU International, 2015.","url":"https://bjui-journals.onlinelibrary.wiley.com/doi/10.1111/bju.13010","source":"BJU 2015"},{"text":"Marquez-Algaba E et al. Aesthet Plast Surg 2020.","url":"https://pubmed.ncbi.nlm.nih.gov/31831387/","source":"APS 2020"}],"internalLinks":[{"slug":"ingrosare-lipofilling","label":"Lipofilling"}],"speakablePassages":["Faloplastia dorsală oferă câștig vizual 2-5 cm flasc."]},
  {"slug":"ingrosare-lipofilling","title":"Îngroșare penis cu lipofilling","h1":"Îngroșare penis cu grăsime proprie","category":"augmentare","procedureType":"SurgicalProcedure","metaTitle":"Îngroșare penis cu grăsime proprie București | Lipofilling | Dr. Diana","metaDescription":"Îngroșare penis prin lipofilling autolog. 1-3 cm circumferință permanent.","primaryKeyword":"îngroșare penis lipofilling","searchVolume":"900-1.300/lună","intent":"Commercial-investigational","bodyLocation":"corp penian","alternateName":["fat grafting"],"shortDescription":"Câștig 1-3 cm circumferință cu grăsime proprie.","lead":"Lipofillingul transferă 30-80 ml grăsime proprie procesată Coleman, oferind 1-3 cm câștig permanent.","cost":"3.000-4.000 EUR","duration":"2 ore","recovery":"5-7 zile","anesthesia":"Locală cu sedare","hospitalStay":"Externare aceeași zi","sexualActivity":"3-4 săptămâni","whatIs":"Recoltare grăsime + procesare Coleman + injectare în țesut subcutan penis. Zero risc respingere.","whenIndicated":["Pacient nemulțumit de circumferință","Combinație cu alungire"],"whenNotIndicated":["Pacient foarte slab","Tulburări coagulare"],"procedureSteps":[{"title":"Recoltare","description":"100-200 ml din abdomen."},{"title":"Procesare Coleman","description":"Centrifugare 3000 rpm."},{"title":"Injectare","description":"Multiple straturi cu canule 17G."}],"facts":[{"label":"Câștig","value":"1-3 cm permanent"},{"label":"Cantitate","value":"30-80 ml"},{"label":"Resorbție","value":"30-50% în 6 luni"},{"label":"Risc respingere","value":"0%"}],"recovery_timeline":[{"period":"Zilele 1-3","title":"Edem","description":"Pansament compresiv."},{"period":"Lună 6","title":"Rezultat stabil","description":"Volumul rămas e permanent."}],"risks":[{"title":"Resorbție","description":"30-50%."},{"title":"Distribuție neuniformă","description":"Noduli mici posibili."}],"alternatives":[{"title":"HA","description":"Reversibil, temporar."}],"faqs":[{"q":"De ce nu silicon?","a":"Produc granuloame, fibroză și deformări permanente."},{"q":"E permanent?","a":"După 6-12 luni stabilizare, da."}],"citations":[{"text":"Coleman SR. Structural fat grafting.","url":"https://pubmed.ncbi.nlm.nih.gov/20978424/","source":"Coleman PRS"}],"internalLinks":[{"slug":"alungire-penis","label":"Alungire"}],"speakablePassages":["Lipofilling oferă 1-3 cm câștig permanent."]},
  {"slug":"ingrosare-acid-hialuronic","title":"Augmentare cu acid hialuronic","h1":"Augmentare penis cu acid hialuronic","category":"augmentare","procedureType":"NonSurgicalProcedure","metaTitle":"Augmentare penis cu acid hialuronic București | Dr. Diana","metaDescription":"Augmentare penis cu HA. Câștig 1-3 cm. Reversibil cu hialuronidază.","primaryKeyword":"augmentare penis acid hialuronic","searchVolume":"600-900/lună","intent":"Commercial","bodyLocation":"țesut subcutan penis","alternateName":["filler peniann"],"shortDescription":"Câștig 1-3 cm cu HA reticulat, reversibil.","lead":"RCT 2021 (J Sex Med) raportează augmentare medie 22,74 mm cu HA filler. Procedura durează 30-45 min, 100% reversibilă.","cost":"600-1.500 EUR","duration":"30-45 min","recovery":"24-48 ore","anesthesia":"Topică + bloc dorsal","hospitalStay":"Ambulator","sexualActivity":"7-10 zile","whatIs":"Augmentare non-chirurgicală cu HA reticulat (Hyacorp MLF1/MLF2, Genefill).","whenIndicated":["Procedură non-chirurgicală","Test pre-lipofilling"],"whenNotIndicated":["Pacient cu kanamicina","Tulburări coagulare"],"procedureSteps":[{"title":"Anestezie","description":"Cremă Emla + bloc dorsal."},{"title":"Injectare","description":"Canulă boantă 22-25G."}],"facts":[{"label":"Câștig (10 ml)","value":"1-2 cm"},{"label":"Durata efectului","value":"12-24 luni"},{"label":"Augmentare medie","value":"22,74 mm","source":"J Sex Med 2021"}],"recovery_timeline":[{"period":"Zilele 1-2","title":"Edem ușor","description":"Sensibilitate locală."},{"period":"Lună 3-6","title":"Stabilizare","description":"HA integrat."}],"risks":[{"title":"Echimoze","description":"5-7 zile."},{"title":"Granulom","description":"<1%."}],"alternatives":[{"title":"Lipofilling","description":"Permanent."}],"faqs":[{"q":"Cât durează?","a":"18 luni media."},{"q":"Pot face HA dacă am kanamicina?","a":"NU. Necesită extracție mai întâi."}],"citations":[{"text":"Yang JR et al. J Sex Med, 2021.","url":"https://pubmed.ncbi.nlm.nih.gov/33988002/","source":"J Sex Med 2021"}],"internalLinks":[{"slug":"ingrosare-lipofilling","label":"Lipofilling"}],"speakablePassages":["Augmentare HA: 1-3 cm câștig, 100% reversibil."]},
  {"slug":"circumcizie-adulti","title":"Circumcizie adulți","h1":"Circumcizie pentru adulți","category":"preput","procedureType":"SurgicalProcedure","metaTitle":"Circumcizie adulți București | Dr. Diana","metaDescription":"Circumcizie adulți, anestezie locală, externare aceeași zi.","primaryKeyword":"circumcizie adulti","searchVolume":"1.000-1.400/lună","intent":"Commercial-investigational","bodyLocation":"preput peniann","alternateName":["tăiere prepuț"],"shortDescription":"Excizie chirurgicală a prepuțului.","lead":"OMS validează reducerea HIV transmisie heterosexuală cu 50-60% (Auvert PLoS Med 2005). Procedura 30-60 min, externare aceeași zi.","cost":"1.500-2.500 EUR","duration":"30-60 min","recovery":"5-7 zile","anesthesia":"Locală 80% cazuri","hospitalStay":"Aceeași zi 99%","sexualActivity":"4-6 săptămâni","whatIs":"Excizia chirurgicală completă a prepuțului.","whenIndicated":["Fimoză strânsă (BXO)","Balanită recurentă","Indicație religioasă"],"whenNotIndicated":["Hipospadias necorectat"],"procedureSteps":[{"title":"Bloc dorsal","description":"Lidocaină 1%."},{"title":"Excizie","description":"5-10 mm sub coroană."},{"title":"Sutură","description":"Resorbabilă 5/0."}],"facts":[{"label":"Reducere risc HIV","value":"50-60%","source":"Auvert PLoS Med 2005"},{"label":"Reducere cancer penian","value":"60-70%"},{"label":"Externare aceeași zi","value":"99%"}],"recovery_timeline":[{"period":"Zilele 1-3","title":"Disconfort moderat","description":"Paracetamol."},{"period":"Săpt. 4-6","title":"Reluare sexuală","description":"După acord medic."}],"risks":[{"title":"Sângerare","description":"1-3%."},{"title":"Stenoză meatală","description":"<1%."}],"alternatives":[{"title":"Preputioplastie","description":"Conservare prepuț."}],"faqs":[{"q":"Schimbă sensibilitatea?","a":"Tian 2013 (J Sex Med): nu există diferență semnificativă."},{"q":"Cât durerea?","a":"3-5 zile, paracetamol."}],"citations":[{"text":"WHO/UNAIDS","url":"https://www.who.int/health-topics/male-circumcision","source":"WHO"},{"text":"Auvert et al PLoS Med 2005","url":"https://pubmed.ncbi.nlm.nih.gov/16231970/","source":"PLoS Med 2005"}],"internalLinks":[{"slug":"alungire-penis","label":"Alungire"}],"speakablePassages":["Circumcizia reduce HIV transmisie cu 50-60% conform OMS."]},
  {"slug":"peyronie-nesbit","title":"Boala Peyronie - Nesbit","h1":"Tehnica Nesbit pentru boala Peyronie","category":"curbura","procedureType":"SurgicalProcedure","metaTitle":"Tratament Peyronie București | Tehnica Nesbit | Dr. Diana","metaDescription":"Corectare curbură penis în Peyronie. Succes 80-100% pe curburi <60°.","primaryKeyword":"boala peyronie tratament chirurgical","searchVolume":"350-500/lună","intent":"Commercial-investigational","bodyLocation":"tunica albuginee","alternateName":["Nesbit procedure"],"shortDescription":"Corectare chirurgicală curbură peniană.","lead":"Tehnica Nesbit corectează curbura prin excizie eliptică tunica albuginee. Succes 80-100% pe curburi <60°. Pierdere lungime 0,5-2 cm.","cost":"3.500-5.500 EUR","duration":"90-120 min","recovery":"14-21 zile","anesthesia":"Generală sau rahidiană","hospitalStay":"1 noapte","sexualActivity":"6-8 săptămâni","whatIs":"Excizia eliptică din tunica albuginee pe partea opusă plăcii + sutură transversală.","whenIndicated":["Curbură <60° fără ED","Stadiu cronic stabil 6 luni"],"whenNotIndicated":["Stadiu acut","Curbură >60-70°","DE severă"],"procedureSteps":[{"title":"Erecție artificială","description":"Documentare curbură."},{"title":"Excizie eliptică","description":"Pe partea opusă plăcii."},{"title":"Sutură transversală","description":"PDS sau Prolene."}],"facts":[{"label":"Prevalența","value":"3-9%","source":"Sommer Eur Urol 2002"},{"label":"Succes pe <60°","value":"80-100%"},{"label":"Pierdere lungime","value":"0,5-2 cm"}],"recovery_timeline":[{"period":"Zilele 1-3","title":"Spitalizare","description":"1 noapte."},{"period":"Săpt. 6-8","title":"Reluare sexuală","description":"După acord medic."}],"risks":[{"title":"Pierdere lungime","description":"0,5-2 cm."},{"title":"Recurență","description":"5-15% la 5 ani."}],"alternatives":[{"title":"Plicatură","description":"Pierde mai puțin."},{"title":"Implant peniann","description":"Pentru DE severă."}],"faqs":[{"q":"Voi pierde lungime?","a":"Da, 0,5-2 cm."},{"q":"Alternativă fără chirurgie?","a":"Xiapex în stadiu acut."}],"citations":[{"text":"AUA Guidelines on Peyronie's Disease","url":"https://www.auanet.org/guidelines/peyronies-disease-guideline","source":"AUA"}],"internalLinks":[{"slug":"peyronie","label":"Peyronie hub"}],"speakablePassages":["Tehnica Nesbit are succes 80-100% pe curburi <60°."]},
  {"slug":"peyronie","title":"Boala Peyronie - ghid","h1":"Boala Peyronie ghid complet","category":"curbura","procedureType":"TherapeuticProcedure","metaTitle":"Boala Peyronie București | Diagnostic și tratament | Dr. Diana","metaDescription":"Boala Peyronie: ghid complet despre stadii, tratamente medicale și chirurgicale.","primaryKeyword":"boala peyronie","searchVolume":"1.300-1.800/lună","intent":"Informational+commercial","bodyLocation":"tunica albuginee","alternateName":["IPP"],"shortDescription":"Hub informațional Peyronie.","lead":"Peyronie afectează 3-9% bărbați adulți (Sommer Eur Urol 2002). Vârsta medie debut 55-60 ani. 10-20% remit spontan.","cost":"Variabil","duration":"Variabilă","recovery":"Variabilă","anesthesia":"Variabilă","hospitalStay":"Variabil","sexualActivity":"Variabil","whatIs":"IPP = afecțiune fibroinflamatorie a tunicii albuginee.","whenIndicated":["Curbură peniană apărută adultate","Durere la erecție"],"whenNotIndicated":["Curbură congenitală"],"procedureSteps":[{"title":"Anamneză","description":"Debut, durere, evoluție."},{"title":"Imagistică","description":"Ecografie peniană."}],"facts":[{"label":"Prevalență","value":"3-9%","source":"Sommer 2002"},{"label":"Remisie spontană","value":"10-20% în 12 luni"}],"recovery_timeline":[],"risks":[{"title":"DE progresivă","description":"20-30%."},{"title":"Scurtare","description":"1-3 cm."}],"alternatives":[{"title":"Conservator","description":"Pentoxifilină, Xiapex."},{"title":"Chirurgical","description":"Plicatură, Nesbit."}],"faqs":[{"q":"Voi avea Peyronie permanent?","a":"10-20% remit spontan."},{"q":"Trebuie să operez?","a":"Doar dacă curbura împiedică actul sexual."}],"citations":[{"text":"AUA Guidelines","url":"https://www.auanet.org/guidelines/peyronies-disease-guideline","source":"AUA"},{"text":"EAU Guidelines 2024","url":"https://uroweb.org/guidelines/sexual-and-reproductive-health/","source":"EAU"}],"internalLinks":[{"slug":"peyronie-nesbit","label":"Nesbit"}],"speakablePassages":["Peyronie afectează 3-9% bărbați adulți."]},
  {"slug":"p-shot-prp","title":"P-Shot / Priapus Shot","h1":"P-Shot - PRP autolog penis","category":"regenerativ","procedureType":"NonSurgicalProcedure","metaTitle":"P-Shot București | PRP penis | Dr. Diana","metaDescription":"P-Shot cu PRP autolog. Indicații pentru DE moderată.","primaryKeyword":"p-shot priapus shot","searchVolume":"200-400/lună","intent":"Commercial-investigational","bodyLocation":"corp penian","alternateName":["Priapus Shot"],"shortDescription":"Injectare PRP autolog. Adjuvant pentru DE.","lead":"P-Shot: injectare plasmă proprie. RCT 2021 (Poulios J Sex Med) - îmbunătățire IIEF-EF moderată. Cleveland Clinic 2024: cercetare insuficientă.","cost":"350-650 EUR","duration":"30-45 min","recovery":"24-48 ore","anesthesia":"Topică + bloc dorsal","hospitalStay":"Ambulator","sexualActivity":"24-48 ore","whatIs":"30-60 ml sânge propriu centrifugat → PRP injectat în corpii cavernoși.","whenIndicated":["DE ușoară-moderată","Adjuvant"],"whenNotIndicated":["DE severă"],"procedureSteps":[{"title":"Recoltare","description":"30-60 ml venos."},{"title":"Centrifugare","description":"8-10 min."},{"title":"Injectare","description":"3-5 puncte."}],"facts":[{"label":"PRP","value":"Platelet-Rich Plasma autolog"},{"label":"Risc respingere","value":"0%"}],"recovery_timeline":[{"period":"Ziua 1","title":"Disconfort minim","description":"Edem ușor."}],"risks":[{"title":"Lipsă răspuns","description":"40-50% pacienți."}],"alternatives":[{"title":"Sildenafil","description":"Standardul."}],"faqs":[{"q":"Funcționează garantat?","a":"50-60% îmbunătățire subiectivă."},{"q":"Crește dimensiunea?","a":"NU. Marketing înșelător."}],"citations":[{"text":"Poulios E. J Sex Med 2021.","url":"https://pubmed.ncbi.nlm.nih.gov/33906807/","source":"J Sex Med 2021"}],"internalLinks":[{"slug":"peyronie","label":"Peyronie"}],"speakablePassages":["P-Shot are evidență moderată pentru DE."]},
  {"slug":"extractie-kanamicina","title":"Extracție kanamicina/silicon","h1":"Extracție corpi străini din penis","category":"reparator","procedureType":"SurgicalProcedure","metaTitle":"Extracție kanamicina silicon vaselină penis București | Dr. Diana","metaDescription":"Extracție corpi străini injectați. Reabilitare anatomie. Discreție absolută.","primaryKeyword":"extractie kanamicina penis","searchVolume":"800-1.200/lună","intent":"Commercial-urgent","bodyLocation":"țesut subcutan penis","alternateName":["extracție silicon"],"shortDescription":"Excizie chirurgicală a corpilor străini injectați.","lead":"Estimăm 5.000-15.000 cazuri active autoinjectare RO. Studiu RO 2018-2022 (Beedasy): 100% pacienți autoinjectați dezvoltă complicații, >70% necesită extracție.","cost":"1.800-3.500 EUR","duration":"1-3 ore","recovery":"14-21 zile","anesthesia":"Generală sau rahidiană","hospitalStay":"1-2 nopți","sexualActivity":"6-12 săptămâni","whatIs":"Excizia chirurgicală a corpilor străini cu reconstrucție tegumentară.","whenIndicated":["Granulom peniann","Deformare","Infecție recurentă"],"whenNotIndicated":["Tulburări coagulare severe","Infecție acută"],"procedureSteps":[{"title":"Imagistică","description":"Ecografie + RMN."},{"title":"Excizie radicală","description":"Granulom + țesut."},{"title":"Reconstrucție","description":"Primară sau grefă."}],"facts":[{"label":"Cazuri RO","value":"5.000-15.000"},{"label":"Complicații","value":"100%","source":"Beedasy 2018-2022"},{"label":"Necesar extracție","value":">70%"},{"label":"Estetic restaurat","value":"70-80%"}],"recovery_timeline":[{"period":"Spitalizare","title":"1-2 nopți","description":"Antibioterapie IV."},{"period":"Lună 6-12","title":"Stabilizare","description":"Faloplastie ulterioară posibilă."}],"risks":[{"title":"Cicatrice extinse","description":"Frecvente."},{"title":"Pierdere țesut","description":"0,5-3 cm."}],"alternatives":[{"title":"Aspirație","description":"Doar silicon lichid recent."}],"faqs":[{"q":"Pot rezolva fără operație?","a":"Nu. Excizia e singurul tratament."},{"q":"Cum garantați discreția?","a":"Protocol GDPR strict, raportare publică zero."}],"citations":[{"text":"Beedasy A — granulom kanamicina (RO).","url":"https://dramit.ro/serviciu/granulom-penian-indus-de-kanamicina-injectabila/","source":"RO study"}],"internalLinks":[{"slug":"alungire-penis","label":"Faloplastie"}],"speakablePassages":["Kanamicina, silicon, vaselină nu pot fi îndepărtate decât chirurgical."]}
];

export const getProcedureBySlug = (slug: string): Procedure | undefined =>
  proceduri.find((p) => p.slug === slug);

export const getAllProcedureSlugs = (): string[] => proceduri.map((p) => p.slug);
